# Paquete Numpy

In [1]:
#scipy
#simpy
#!pip install numpy==1.18
import numpy as np

# Numpy Array

In [2]:
my_list = [1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[6,7,8]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

# Métodos en Numpy

In [7]:
np.array(list(range(0,10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.empty((10,10))

array([[4.68391362e-310, 6.90874028e-310, 6.90874028e-310,
        6.90874022e-310, 6.90874028e-310, 6.90874022e-310,
        6.90874028e-310, 6.90874028e-310, 6.90874028e-310,
        6.90874019e-310],
       [6.90874028e-310, 6.90874015e-310, 6.90874015e-310,
        6.90874015e-310, 6.90874015e-310, 6.90874015e-310,
        6.90874022e-310, 6.90874017e-310, 6.90874015e-310,
        6.90874015e-310],
       [6.90874015e-310, 6.90874015e-310, 6.90874015e-310,
        6.90874015e-310, 6.90874015e-310, 6.90874015e-310,
        6.90874015e-310, 6.90874015e-310, 6.90874015e-310,
        6.90874015e-310],
       [6.90874015e-310, 6.90874015e-310, 6.90874015e-310,
        6.90874015e-310, 6.90874015e-310, 6.90874015e-310,
        6.90874015e-310, 6.90874015e-310, 6.90874015e-310,
        6.90874015e-310],
       [6.90874015e-310, 6.90874017e-310, 6.90874017e-310,
        6.90874015e-310, 6.90874019e-310, 6.90874015e-310,
        6.90874015e-310, 6.90874015e-310, 6.90874015e-310,
        6.9

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# Random

## Rand

In [21]:
np.random.rand(10)

array([0.0212538 , 0.50262287, 0.12730965, 0.76493617, 0.57604641,
       0.74046774, 0.43728287, 0.47928067, 0.64828438, 0.02441684])

In [22]:
np.random.rand(5,5)

array([[0.65841973, 0.25999426, 0.81927794, 0.01032883, 0.48515158],
       [0.58749551, 0.88398275, 0.5970703 , 0.82714142, 0.40381425],
       [0.44733148, 0.60467704, 0.22245337, 0.53852912, 0.50785538],
       [0.35660976, 0.11108977, 0.03736747, 0.72423982, 0.19230978],
       [0.91995832, 0.47516393, 0.0981487 , 0.33001398, 0.8528538 ]])

## RandN

In [23]:
np.random.randn(5)

array([-0.86677069, -0.11945504, -0.97001765, -0.44144287, -0.5782076 ])

In [24]:
np.random.randn(5,5)

array([[-0.1051148 ,  1.17133494,  1.02234578, -0.865032  , -1.1598271 ],
       [ 2.29897004,  0.85350461, -0.56478401,  1.9937082 ,  1.90346397],
       [-0.73019007,  0.27085672,  0.48757313, -0.46581918, -0.99569405],
       [-0.74409315, -0.49995578, -0.6832948 ,  0.95339862,  1.09692194],
       [-0.31364454, -1.29098284, -0.51774504,  0.96776654,  1.01002226]])

## RandInt

In [25]:
np.random.randint(0,150)

22

In [26]:
np.random.randint(20,540,50)

array([ 98, 204, 332, 114, 339, 408,  45, 313, 473, 379, 424, 127, 280,
       142, 146, 415, 227, 209, 124, 436, 294,  66, 161, 474, 199, 519,
       375, 357, 420, 219, 495, 353, 243, 113, 320, 407, 293, 504, 161,
       476, 255, 524, 248, 408, 427, 486, 403, 213, 136, 254])

In [27]:
np.random.randint(20,540,(5,5))

array([[348, 159, 138,  64, 372],
       [116, 225,  69, 355, 133],
       [514,  22, 262, 461, 536],
       [345,  36, 484, 198, 251],
       [328, 430, 235, 508, 336]])

In [28]:
x = np.random.randint(20,540,(5,5))
x

array([[478, 379, 234, 388, 268],
       [509,  74, 331, 414, 231],
       [422, 294,  21, 382, 418],
       [393, 306, 183, 104, 410],
       [ 21, 403, 445, 437, 503]])

# Atributos

In [30]:
x.shape

(5, 5)

In [31]:
my_list.shape

AttributeError: ignored

In [32]:
li = np.arange(0,12)
li

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
len(li)

12

In [35]:
lix=li.reshape(3,4)
lix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
li

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
2**2

4

In [39]:
np.power(2,3)

8

In [41]:
np.sqrt(25)

5.0

In [43]:
np.exp(2)

7.38905609893065

In [45]:
p = np.random.randint(20,540,10)
p

array([197, 239,  65, 121,  46, 530, 275,  45,  54, 270])

In [46]:
p.max()

530

In [47]:
np.max(p)

530

In [48]:
p.min()

45

In [49]:
p.mean()

184.2

In [50]:
p.std()

145.5958790625614

In [51]:
p.argmax()

5

In [52]:
np.pi

3.141592653589793

In [54]:
np.exp(1)

2.718281828459045

In [55]:
np.log(100)

4.605170185988092

In [56]:
# math
# funciones matemáticas básicas

# Operaciones 

In [59]:
p

array([197, 239,  65, 121,  46, 530, 275,  45,  54, 270])

In [57]:
p+p

array([ 394,  478,  130,  242,   92, 1060,  550,   90,  108,  540])

In [58]:
p*p

array([ 38809,  57121,   4225,  14641,   2116, 280900,  75625,   2025,
         2916,  72900])

In [60]:
197**2

38809

In [61]:
np.dot(p,p)

551278

In [62]:
0/0

ZeroDivisionError: ignored

In [64]:
np.nan

nan

In [66]:
t = np.arange(0,10)

In [67]:
t/t

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [68]:
p**3

array([  7645373,  13651919,    274625,   1771561,     97336, 148877000,
        20796875,     91125,    157464,  19683000])

In [69]:
np.sqrt(p)

array([14.03566885, 15.45962483,  8.06225775, 11.        ,  6.78232998,
       23.02172887, 16.58312395,  6.70820393,  7.34846923, 16.43167673])

In [70]:
np.exp(p)

array([3.59760050e+085, 6.25721640e+103, 1.69488924e+028, 3.54513118e+052,
       9.49611942e+019, 1.49994526e+230, 2.69763087e+119, 3.49342711e+019,
       2.83075330e+023, 1.81764939e+117])

In [71]:
np.max(p)

530

In [72]:
np.sin(p)

array([ 0.79580584,  0.23669068,  0.82682868,  0.99881522,  0.90178835,
        0.80111655, -0.99388533,  0.85090352, -0.55878905, -0.17604595])

In [73]:
np.cos(p)

array([-0.60555186,  0.97158506, -0.56245385, -0.04866361, -0.43217794,
       -0.59850837,  0.1104172 ,  0.52532199, -0.82930983,  0.98438195])

In [76]:
arr = np.array([11,12,13,14,15,16,17,15,11,12,14,15,16,17])
arr

array([11, 12, 13, 14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])

In [80]:
result = np.where(arr==15)
result

(array([ 4,  7, 11]),)

In [81]:
arr[result]

array([15, 15, 15])

# Indexación 1D

In [82]:
arr[5]

16

In [84]:
x=arr[3:-1]
x

array([14, 15, 16, 17, 15, 11, 12, 14, 15, 16])

In [85]:
arr[-1]

17

In [86]:
arr[3:]

array([14, 15, 16, 17, 15, 11, 12, 14, 15, 16, 17])

In [87]:
arr[2:5]=100

In [88]:
arr

array([ 11,  12, 100, 100, 100,  16,  17,  15,  11,  12,  14,  15,  16,
        17])

# Indexación 2D

In [91]:
m = np.array(my_matrix)
m

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [92]:
m[0,0]

1

In [93]:
m[0][0]

1

In [96]:
m[0:2][1:]

array([[4, 5, 6]])

In [97]:
m[0:2,1:]

array([[2, 3],
       [5, 6]])

In [99]:
### no hagan esto
A = m 
A

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [101]:
n = np.copy(m)
n

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [102]:
t

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
t[(t<5) and (t>8)]

ValueError: ignored

In [109]:
#t[np.and()]
np.logical_or(t<5,t>8)

array([ True,  True,  True,  True,  True, False, False, False, False,
        True])

In [110]:
t[np.logical_or(t<5,t>8)]

array([0, 1, 2, 3, 4, 9])

# FIN